### PR TITLE
Add tests to sdist

### LINKED ISSUE #678: Distributing tests in PyPI tarball
It is often preferable for distributions to refer to PyPI tarballs rather than github ones. This is because PyPI does a better job at making sure that releases aren't retroactively changed, whereas on github this often happens, leading to checksum errors.

Gentoo distributes you package, but sadly we cannot provide testing support if we use PyPI, as the test files are not included:

```
[deco]/tmp/param ❱ tar xvf param-1.12.3.tar.gz
param-1.12.3/
param-1.12.3/LICENSE.txt
param-1.12.3/MANIFEST.in
param-1.12.3/PKG-INFO
param-1.12.3/README.md
param-1.12.3/numbergen/
param-1.12.3/numbergen/__init__.py
param-1.12.3/param/
param-1.12.3/param/.version
param-1.12.3/param/__init__.py
param-1.12.3/param/_async.py
param-1.12.3/param/ipython.py
param-1.12.3/param/parameterized.py
param-1.12.3/param/serializer.py
param-1.12.3/param/version.py
param-1.12.3/param.egg-info/
param-1.12.3/param.egg-info/PKG-INFO
param-1.12.3/param.egg-info/SOURCES.txt
param-1.12.3/param.egg-info/dependency_links.txt
param-1.12.3/param.egg-info/requires.txt
param-1.12.3/param.egg-info/top_level.txt
param-1.12.3/setup.cfg
param-1.12.3/setup.py
[deco]/tmp/param ❱ wget https://github.com/holoviz/param/archive/refs/tags/v1.12.3.tar.gz
--2023-01-14 08:18:41--  https://github.com/holoviz/param/archive/refs/tags/v1.12.3.tar.gz
Resolving github.com... 140.82.112.3
Connecting to github.com|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/holoviz/param/tar.gz/refs/tags/v1.12.3 [following]
--2023-01-14 08:18:41--  https://codeload.github.com/holoviz/param/tar.gz/refs/tags/v1.12.3
Resolving codeload.github.com... 140.82.112.10
Connecting to codeload.github.com|140.82.112.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘v1.12.3.tar.gz’

v1.12.3.tar.gz                                                             [  <=>                                                                                                                                                                       ] 449.80K  1.65MB/s    in 0.3s

2023-01-14 08:18:42 (1.65 MB/s) - ‘v1.12.3.tar.gz’ saved [460593]

[deco]/tmp/param ❱ tar xvf v1.12.3.tar.gz
param-1.12.3/
param-1.12.3/.coveragerc
param-1.12.3/.gitattributes
param-1.12.3/.github/
param-1.12.3/.github/workflows/
param-1.12.3/.github/workflows/build.yaml
param-1.12.3/.github/workflows/docs.yaml
param-1.12.3/.github/workflows/downstream_tests.yaml
param-1.12.3/.github/workflows/test.yaml
param-1.12.3/.gitignore
param-1.12.3/.gitmodules
param-1.12.3/LICENSE.txt
param-1.12.3/MANIFEST.in
param-1.12.3/README.md
param-1.12.3/binder/
param-1.12.3/binder/environment.yml
param-1.12.3/binder/postBuild
param-1.12.3/conda.recipe/
param-1.12.3/conda.recipe/meta.yaml
param-1.12.3/doc/
param-1.12.3/doc/_static/
param-1.12.3/doc/_static/favicon.ico
param-1.12.3/doc/_static/icon.png
param-1.12.3/doc/_static/icon.svg
param-1.12.3/doc/_static/logo.png
param-1.12.3/doc/_static/logo_horizontal.png
param-1.12.3/doc/_static/logo_horizontal.svg
param-1.12.3/doc/_static/logo_horizontal_white.png
param-1.12.3/doc/_static/logo_horizontal_white.svg
param-1.12.3/doc/_static/logo_stacked.png
param-1.12.3/doc/_static/logo_stacked.svg
param-1.12.3/doc/_static/site.css
param-1.12.3/doc/_static/wordmark.png
param-1.12.3/doc/_static/wordmark.svg
param-1.12.3/doc/about.md
param-1.12.3/doc/comparisons.md
param-1.12.3/doc/conf.py
param-1.12.3/doc/getting_started.md
param-1.12.3/doc/index.md
param-1.12.3/doc/reference.rst
param-1.12.3/doc/releases.md
param-1.12.3/doc/roadmap.md
param-1.12.3/doc/user_guide/
param-1.12.3/doc/user_guide/index.md
param-1.12.3/examples/
param-1.12.3/examples/Promo.ipynb
param-1.12.3/examples/assets/
param-1.12.3/examples/assets/logo_stacked.png
param-1.12.3/examples/assets/param-is-powerful.png
param-1.12.3/examples/assets/param_help.png
param-1.12.3/examples/user_guide/
param-1.12.3/examples/user_guide/Dependencies_and_Watchers.ipynb
param-1.12.3/examples/user_guide/Dynamic_Parameters.ipynb
param-1.12.3/examples/user_guide/How_Param_Works.ipynb
param-1.12.3/examples/user_guide/Logging_and_Warnings.ipynb
param-1.12.3/examples/user_guide/Outputs.ipynb
param-1.12.3/examples/user_guide/Parameter_Types.ipynb
param-1.12.3/examples/user_guide/ParameterizedFunctions.ipynb
param-1.12.3/examples/user_guide/Parameters.ipynb
param-1.12.3/examples/user_guide/Serialization_and_Persistence.ipynb
param-1.12.3/examples/user_guide/Simplifying_Codebases.ipynb
param-1.12.3/numbergen/
param-1.12.3/numbergen/__init__.py
param-1.12.3/param/
param-1.12.3/param/__init__.py
param-1.12.3/param/_async.py
param-1.12.3/param/ipython.py
param-1.12.3/param/parameterized.py
param-1.12.3/param/serializer.py
param-1.12.3/param/version.py
param-1.12.3/setup.cfg
param-1.12.3/setup.py
param-1.12.3/tests/
param-1.12.3/tests/API0/
param-1.12.3/tests/API0/__init__.py
param-1.12.3/tests/API0/testcalendardateparam.py
param-1.12.3/tests/API0/testcalendardaterangeparam.py
param-1.12.3/tests/API0/testclassselector.py
param-1.12.3/tests/API0/testcolorparameter.py
param-1.12.3/tests/API0/testcompositeparams.py
param-1.12.3/tests/API0/testdateparam.py
param-1.12.3/tests/API0/testdaterangeparam.py
param-1.12.3/tests/API0/testdefaults.py
param-1.12.3/tests/API0/testdynamicparams.py
param-1.12.3/tests/API0/testipythonmagic.py
param-1.12.3/tests/API0/testlistselector.py
param-1.12.3/tests/API0/testnumbergen.py
param-1.12.3/tests/API0/testnumpy.py
param-1.12.3/tests/API0/testobjectselector.py
param-1.12.3/tests/API0/testparameterizedobject.py
param-1.12.3/tests/API0/testparameterizedrepr.py
param-1.12.3/tests/API0/testrangeparameter.py
param-1.12.3/tests/API0/teststringparam.py
param-1.12.3/tests/API0/testtimedependent.py
param-1.12.3/tests/API1/
param-1.12.3/tests/API1/__init__.py
param-1.12.3/tests/API1/testcalendardateparam.py
param-1.12.3/tests/API1/testcalendardaterangeparam.py
param-1.12.3/tests/API1/testclassselector.py
param-1.12.3/tests/API1/testcolorparameter.py
param-1.12.3/tests/API1/testcomparator.py
param-1.12.3/tests/API1/testcompositeparams.py
param-1.12.3/tests/API1/testdateparam.py
param-1.12.3/tests/API1/testdaterangeparam.py
param-1.12.3/tests/API1/testdefaults.py
param-1.12.3/tests/API1/testdynamicparams.py
param-1.12.3/tests/API1/testipythonmagic.py
param-1.12.3/tests/API1/testjsonserialization.py
param-1.12.3/tests/API1/testlist.py
param-1.12.3/tests/API1/testlistselector.py
param-1.12.3/tests/API1/testnumbergen.py
param-1.12.3/tests/API1/testnumberparameter.py
param-1.12.3/tests/API1/testnumpy.py
param-1.12.3/tests/API1/testobjectselector.py
param-1.12.3/tests/API1/testpandas.py
param-1.12.3/tests/API1/testparamdepends.py
param-1.12.3/tests/API1/testparamdepends_py3.py
param-1.12.3/tests/API1/testparameterizedobject.py
param-1.12.3/tests/API1/testparameterizedrepr.py
param-1.12.3/tests/API1/testparamoutput.py
param-1.12.3/tests/API1/testparamunion.py
param-1.12.3/tests/API1/testrangeparameter.py
param-1.12.3/tests/API1/testselector.py
param-1.12.3/tests/API1/teststringparam.py
param-1.12.3/tests/API1/testtimedependent.py
param-1.12.3/tests/API1/testutils.py
param-1.12.3/tests/API1/testwatch.py
param-1.12.3/tests/API1/utils.py
param-1.12.3/tests/README.md
param-1.12.3/tests/__init__.py
param-1.12.3/tox.ini
param-1.12.3/tox27.ini
```

would you be interested in adding the tests to your PyPI tarballs in the future, same as you already do on GH?

### PR DESCRIPTION
**Pull request by ianthomas23**
Fixes #678.

This PR adds the `tests` directory to the `sdist` so that those who build the library from the `sdist` rather than github repo have access to the tests. This includes Linux distribution packagers.

Contents of `sdist` are now:
```
$ tar tf param-1.12.3.post6+g00d89ba.tar.gz
param-1.12.3.post6+g00d89ba/
param-1.12.3.post6+g00d89ba/LICENSE.txt
param-1.12.3.post6+g00d89ba/MANIFEST.in
param-1.12.3.post6+g00d89ba/PKG-INFO
param-1.12.3.post6+g00d89ba/README.md
param-1.12.3.post6+g00d89ba/numbergen/
param-1.12.3.post6+g00d89ba/numbergen/__init__.py
param-1.12.3.post6+g00d89ba/param/
param-1.12.3.post6+g00d89ba/param/.version
param-1.12.3.post6+g00d89ba/param/__init__.py
param-1.12.3.post6+g00d89ba/param/_async.py
param-1.12.3.post6+g00d89ba/param/ipython.py
param-1.12.3.post6+g00d89ba/param/parameterized.py
param-1.12.3.post6+g00d89ba/param/serializer.py
param-1.12.3.post6+g00d89ba/param/version.py
param-1.12.3.post6+g00d89ba/param.egg-info/
param-1.12.3.post6+g00d89ba/param.egg-info/PKG-INFO
param-1.12.3.post6+g00d89ba/param.egg-info/SOURCES.txt
param-1.12.3.post6+g00d89ba/param.egg-info/dependency_links.txt
param-1.12.3.post6+g00d89ba/param.egg-info/requires.txt
param-1.12.3.post6+g00d89ba/param.egg-info/top_level.txt
param-1.12.3.post6+g00d89ba/setup.cfg
param-1.12.3.post6+g00d89ba/setup.py
param-1.12.3.post6+g00d89ba/tests/
param-1.12.3.post6+g00d89ba/tests/API0/
param-1.12.3.post6+g00d89ba/tests/API0/__init__.py
param-1.12.3.post6+g00d89ba/tests/API0/testcalendardateparam.py
param-1.12.3.post6+g00d89ba/tests/API0/testcalendardaterangeparam.py
param-1.12.3.post6+g00d89ba/tests/API0/testclassselector.py
param-1.12.3.post6+g00d89ba/tests/API0/testcolorparameter.py
param-1.12.3.post6+g00d89ba/tests/API0/testcompositeparams.py
param-1.12.3.post6+g00d89ba/tests/API0/testdateparam.py
param-1.12.3.post6+g00d89ba/tests/API0/testdaterangeparam.py
param-1.12.3.post6+g00d89ba/tests/API0/testdefaults.py
param-1.12.3.post6+g00d89ba/tests/API0/testdynamicparams.py
param-1.12.3.post6+g00d89ba/tests/API0/testipythonmagic.py
param-1.12.3.post6+g00d89ba/tests/API0/testlistselector.py
param-1.12.3.post6+g00d89ba/tests/API0/testnumbergen.py
param-1.12.3.post6+g00d89ba/tests/API0/testnumpy.py
param-1.12.3.post6+g00d89ba/tests/API0/testobjectselector.py
param-1.12.3.post6+g00d89ba/tests/API0/testparameterizedobject.py
param-1.12.3.post6+g00d89ba/tests/API0/testparameterizedrepr.py
param-1.12.3.post6+g00d89ba/tests/API0/testrangeparameter.py
param-1.12.3.post6+g00d89ba/tests/API0/teststringparam.py
param-1.12.3.post6+g00d89ba/tests/API0/testtimedependent.py
param-1.12.3.post6+g00d89ba/tests/API1/
param-1.12.3.post6+g00d89ba/tests/API1/__init__.py
param-1.12.3.post6+g00d89ba/tests/API1/testbytesparam.py
param-1.12.3.post6+g00d89ba/tests/API1/testcalendardateparam.py
param-1.12.3.post6+g00d89ba/tests/API1/testcalendardaterangeparam.py
param-1.12.3.post6+g00d89ba/tests/API1/testclassselector.py
param-1.12.3.post6+g00d89ba/tests/API1/testcolorparameter.py
param-1.12.3.post6+g00d89ba/tests/API1/testcomparator.py
param-1.12.3.post6+g00d89ba/tests/API1/testcompositeparams.py
param-1.12.3.post6+g00d89ba/tests/API1/testdateparam.py
param-1.12.3.post6+g00d89ba/tests/API1/testdaterangeparam.py
param-1.12.3.post6+g00d89ba/tests/API1/testdefaults.py
param-1.12.3.post6+g00d89ba/tests/API1/testdynamicparams.py
param-1.12.3.post6+g00d89ba/tests/API1/testipythonmagic.py
param-1.12.3.post6+g00d89ba/tests/API1/testjsonserialization.py
param-1.12.3.post6+g00d89ba/tests/API1/testlist.py
param-1.12.3.post6+g00d89ba/tests/API1/testlistselector.py
param-1.12.3.post6+g00d89ba/tests/API1/testnumbergen.py
param-1.12.3.post6+g00d89ba/tests/API1/testnumberparameter.py
param-1.12.3.post6+g00d89ba/tests/API1/testnumpy.py
param-1.12.3.post6+g00d89ba/tests/API1/testobjectselector.py
param-1.12.3.post6+g00d89ba/tests/API1/testpandas.py
param-1.12.3.post6+g00d89ba/tests/API1/testparamdepends.py
param-1.12.3.post6+g00d89ba/tests/API1/testparamdepends_py3.py
param-1.12.3.post6+g00d89ba/tests/API1/testparameterizedobject.py
param-1.12.3.post6+g00d89ba/tests/API1/testparameterizedrepr.py
param-1.12.3.post6+g00d89ba/tests/API1/testparamoutput.py
param-1.12.3.post6+g00d89ba/tests/API1/testparamunion.py
param-1.12.3.post6+g00d89ba/tests/API1/testrangeparameter.py
param-1.12.3.post6+g00d89ba/tests/API1/testselector.py
param-1.12.3.post6+g00d89ba/tests/API1/teststringparam.py
param-1.12.3.post6+g00d89ba/tests/API1/testtimedependent.py
param-1.12.3.post6+g00d89ba/tests/API1/testutils.py
param-1.12.3.post6+g00d89ba/tests/API1/testwatch.py
param-1.12.3.post6+g00d89ba/tests/API1/utils.py
param-1.12.3.post6+g00d89ba/tests/README.md
param-1.12.3.post6+g00d89ba/tests/__init__.py
```

I have not added the `docs` directory to the `sdist`; there is an argument for doing so alongside this.

### CODE REVIEW

**Comment by droumis** [comment]
@ianthomas23 do you want to take a look at the CI?

**Comment by ianthomas23** [comment]
The test failures aren't related to the change in this PR. CI is in catastrophic failure mode.

**Comment by ianthomas23** [comment]
Rebased to pick up CI fixes.

**Comment by maximlt** [comment]
Superseded by https://github.com/holoviz/param/pull/749

**Pull request closed without merging**
