### PR TITLE
Param Promo Example

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
Used for solving https://github.com/holoviz/param/issues/486#issuecomment-862041017

### CODE REVIEW

**Comment by philippjfr** [comment]
@MarcSkovMadsen Could you move this branch to param and reopen the PR from there so it's easier for you and @ea42gh to collaborate?

**Comment by jbednar** [comment]
Yes, please do make a branch for it; I'll have some fixes to push as well. Also, please do not include examples/.ipynb_checkpoints/Introduction-checkpoint.ipynb in the new PR. Thanks!

**Comment by ea42gh** [comment]
@MarcSkovMadsen please let me know what you named the branch

**Comment by MarcSkovMadsen** [comment]
This PR is replaced by https://github.com/holoviz/param/pull/488

**Pull request closed without merging**
