### PR TITLE
Improve DateRange validation

### PR DESCRIPTION
**Pull request by maximlt**
Noticed that the `DateRange` parameter was not checking that the value provided is a `tuple`, which it should be given that `DateRange` inherits from Tuple.

I've also changed the error message reported when one of the values is not of the correct type:

    DateRange parameter 'a' only takes date/datetime values, not type float.

This is slightly different formatting compared to the messages reported by other Parameters, e.g. with a List:

    List parameter None must be a list, not an object of type <class 'str'>.

Notice `of type float` vs. `of type <class 'str'>`. If the latter is preferred, I could update the error messages of the other Parameters.

### CODE REVIEW

**Comment by maximlt** [comment]
@jlstevens ready for review 🙃

**Review by jlstevens — APPROVED** [review]

**Comment by jlstevens** [comment]
Looks good to me!

**Review by jbednar — APPROVED** [review]
Looks good to me, thanks! I agree that it would be nice to make messages more consistent, but don't have a terribly strong opinion between the ways that type information is printed. I think on balance I'd prefer a simpler, more-English like version (e.g. `type float`) over a syntax-y version (e.g. `<class 'float'>`).

**Comment by philippjfr** [comment]
Agreed, consistency would be good but for now this is an improvement.

**Pull request merged**
