### PR TITLE
Promotion Initiative

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
This PR adds some of the ideas from https://github.com/holoviz/param/issues/486 like a Promo Notebook with an associated Video.

Replaces https://github.com/holoviz/param/pull/487

FYI @ea42gh @jbednar

### CODE REVIEW

**Comment by jbednar** [comment]
Thanks, @MarcSkovMadsen! I've pushed some minor cleanups, but otherwise it looks great! 

The notebook wasn't formatting properly in classic Jupyter (all the logos were showing up in one vertical line). I fixed that by putting everything in a table, which works well in classic Jupyter; hope that also works in JupyterLab (and hope nothing else I did messed up the incremental display for JupyterLab).

The example looks good. Some notes:
1. It's annoying that the Parameterized class needs a constructor, because very often a Parameterized class does not, and this one is about the most complex code being shown here. I can't think of how to avoid it if we want c to be initialized at first, though. That may be a small hole in Param that we could fill somehow, i.e. add `init=True` alongside `watch=True` to ensure that the dependent code is run during initialization.
2. Do we need to cover the bit with a separate watcher?  I'm not sure that most users will be able to see why that's relevant to them immediately, and I think the limit for a video like this is about 5 minutes, so it would be good to find something to cut.
3. It's a shame to have to include try/except in the first intro video; not everyone is comfortable catching exceptions, and it's quite wordy. In my other docs I'm using a context manager `with exceptions_summarized()` for that reason, which is shorter, but then that has to be imported and people aren't necessarily comfortable with context managers either. I guess that's another hole in Param; we should have some variable we can set that gives us short exceptions printing, for cases like this.
4. There are lots of other things Param provides; obviously we can't include all of them, so this is as good a set as any to start with, I suppose!

**Comment by ea42gh** [comment]
Fortunately, folding works in both jupyter classic and jupyter lab.
In classic, one needs to enable an nbextension...

**Comment by maximlt** [comment]
ipython has a `%xmode` magic command that is a switch affecting the length of tracebacks displayed. Its minimal mode displays only one line. See its [doc](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-xmode). That's a potential alternative to the context manager or the try ... except block.

**Comment by jbednar** [comment]
True; that could work here! Thanks. I don't think it would help for the docs in general, because the docs need some way to indicate that the exception is expected and that execution should not halt.

**Comment by ea42gh** [comment]
I took my copy of Promo.ipynb and used %xmode
The video will be cleaner that way, but I would leave the original version with the
block to catch the exception...

**Comment by jbednar** [comment]
Looks good; merging!

**Pull request merged**
