### PR TITLE
Updated JSON serialization of Date and CalendarDate to support None

### PR DESCRIPTION
**Pull request by jlstevens**
Simple fix that addresses https://github.com/holoviz/param/issues/578 issue for `None` valued `Date` parameters and does the same for `CalendarDate` parameters.

### CODE REVIEW

**Comment by jlstevens** [comment]
@jbednar @philippjfr Ready for review assuming the tests go green on CI (they work fine locally).

**Comment by jlstevens** [comment]
Tests have passed except for the pypy suite due to an unrelated issue.

**Comment by jlstevens** [comment]
Thanks for prompting me to have another look!

I realize that my initial impression *was* correct and `JSONNullable` is applied even for the special schema methods. I'll push a commit now to revert that unnecessary change.

Otherwise it is about checking how the `serialize` and `deserialize` handle `'null`'. The full list of parameters using these methods are: `Tuple`, `Array`, `DataFrame`, `Date` (done) and `CalendarDate` (done).

I'll make sure `Tuple`, `Array`, `DataFrame` work properly now.

**Comment by jlstevens** [comment]
>  I think users will expect those classes to behave the same in all cases apart from the type, so for futureproofing we could consider refactoring them into a BaseDate class with a strformat parameter ("%Y-%m-%d" vs. "%Y-%m-%dT%H:%M:%S.%f"), or just making Date be that baseclass and having very little code in CalendarDate so that those two classes always stay in sync.

At a glance that does look to be true but looking closer there isn't *that* much shared. The `isinstance` checks are different and other than the `strformat` format,   `CalendarDate` uses the [`.date()` method](https://github.com/holoviz/param/blob/master/param/__init__.py#L1966). So on balance I don't think there is *that* strong an incentive to make a base class.

**Comment by jbednar** [comment]
Ah, didn't spot ".date()".  Ok, keeping them separate is fine. Having a general declarative implementation of the instance checks across many Parameter types would be a separate task, but would seem to simplify things.

**Comment by jlstevens** [comment]
@philippjfr @jbednar Any idea what the rationale might have been to hardcode `allow_None=True` for `Array`? Is there a reason arrays always have to accept `None`?

```python
class Array(ClassSelector):
    """
    Parameter whose value is a numpy array.
    """

    def __init__(self, default=None, **params):
        from numpy import ndarray
        super(Array, self).__init__(ndarray, allow_None=True, default=default, **params)
```

**Comment by jbednar** [comment]
I would assume that's because Pandas is not a required dependency and thus we can't have an array as the default value. That said, I think the right thing to do is to have the default be None but _not_ specify `allow_None`, so that when someone instantiates their own Array parameter they can put their own default in, typically non-None, and then separately decide whether to allow None. That's a breaking change, but I think it's the right thing to do, as I don't think `allow_None` should have been hardcoded except when using the default None value.

**Comment by jlstevens** [comment]
Your suggestion about `allow_None` makes sense to me and should be put into another issue.

Otherwise, I have added None/'null' support for `Tuple`, `Array` and `DataFrame`. Ready for review/merge once more.

**Review by jbednar — APPROVED** [review]
Looks good, but please consistently choose _either_ an early return style:

```python
if value is None:
    return 'null'

return val...
```
_or_ an if/else:

```python
if value is None:
    return 'null'
else:
    return val...
```

Right now it's a mix of the two, and thus less easy to scan.

**Review by jbednar — APPROVED** [review]

**Pull request merged**
