### PR TITLE
Make `Parameterized.initialized` private

### PR DESCRIPTION
**Pull request by maximlt**
I think this one slipped through the cracks until now, but it was noted in the Param 2.0 plan that it should be made private https://github.com/holoviz/param/issues/543

### CODE REVIEW

**Comment by maximlt** [comment]
Hmm that's why I don't like so much internal attributes on a Parameterized class, they can easily clash with user code:

- https://github.com/holoviz/panel/blob/e93b963751cf3ca1219fcfcfc66461047a3f842e/panel/pane/holoviews.py#L108
- https://github.com/holoviz/lumen/blob/7f4d22a2b47ec6ea2209bc90a915398786a00e72/lumen/views/base.py#L135
- https://github.com/holoviz-topics/EarthSim/blob/5d6bde55feaa6e95e292a90575dfc5179f5b3beb/earthsim/grabcut.py#L190

I really wonder what's the best way to avoid this kind of situation. Mangling? Relying on a private namespace a la `.param`?

**Comment by jlstevens** [comment]
Thanks for this! 

As you know, this particular issue recently bit me.

I think *both* `initialized` and `_initialized` are common and likely to clash. As you say, attributes on parameterized classes often cause clashing namespaces: for this reason I suggest replace `.initialized` with something even less likely to be problematic e.g. `_initialized_` (two underscores should do the trick!)

**Comment by Hoxbro** [comment]
I agree with @jlstevens about the high likelihood of a name clash, though I would suggest `__initialized` instead. This is because I never _really_ look at the end of the variable but always at the start.

**Comment by jbednar** [comment]
I agree with the goal of this PR, but I also agree with the observation that `_initialization` is also a common idiom, and so I'm not sure it's the right fix. `__initialized` seems fine if it can be made to work, or else putting such attributes under .param in in a very obscurely named attribute seems better.

**Comment by jlstevens** [comment]
If sticking `_initialized` on the param namespace object works and is easier than dealing with name mangling, I think that would be a big improvement.

**Comment by maximlt** [comment]
Superseded by https://github.com/holoviz/param/pull/766

**Pull request closed without merging**
