### PR TITLE
Run tests on Python 3.12

### PR DESCRIPTION
**Pull request by maximlt**

### CODE REVIEW

**Comment by ianthomas23** [comment]
It should be `3.12-dev` rather than `3.12`.

**Comment by ianthomas23** [comment]
for the `setup-python` action I mean.

**Comment by maximlt** [comment]
> It should be `3.12-dev` rather than `3.12`.

Oh I didn't see your message, instead I just tried setting `allow-prereleases` to `true` for the `setup-python` action (https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#allow-pre-releases) and it seems it worked.

**Comment by maximlt** [comment]
It is! Merging.

**Pull request merged**
